[package]
name = "nju-schedule-ics"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.3"
anyhow = "1.0.75"
axum = "0.6.20"
axum-macros = "0.3.8"
base64 = "0.21.2"
cbc = { version = "0.1.2", features = ["alloc", "std"] }
chrono = "0.4.29"
ics = "0.5.8"
json = "0.12.4"
reqwest = { version = "0.11.18", features = ["cookie_store", "cookies"] }
reqwest-middleware = "0.2.3"
reqwest-retry = "0.2.3"
serde = { version = "1.0.188", features = ["derive"] }
tl = "0.7.7"
tokio = { version = "1.29.1", features = ["macros"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
