# The path to SQLite database
# which stores cookies
db_path="./cookies.sqlite"

# The base URL of this site
# Don't add the trailing slash
site_url="http://localhost:8899"

# Listen address&port
# This is different from site_url, as you'll probably
# use a reverse proxy in front of this.
listen_addr="0.0.0.0:8899"